name: CICD

on:
  push:
    branches: [ "main", "release/*" ]
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          # https://github.com/actions/checkout/issues/116#issuecomment-644419389
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: 'recursive'
    - uses: actions/setup-dotnet@v4
      with:
          dotnet-version: '9.0.x'

    - name: Install workloads
      run: dotnet workload install android

    - name: CreateNugetPackages
      env:
        BABEL_LICENSE: ${{ secrets.BABEL_LICENSE_SECRET }}
      run: dotnet run --project ${{github.workspace}}/build/_build.csproj -- --target CreateNugetPackages --configuration Release --output ${{github.workspace}}/artifacts/packages/

    - name: Upload Avalonia nupkg artifact
      uses: actions/upload-artifact@v4
      with:
        name: avalonia
        path: ${{github.workspace}}/artifacts/packages/Avalonia.Controls.WebView.*.nupkg
        retention-days: 1
    - name: Upload XPF nupkg artifact
      uses: actions/upload-artifact@v4
      with:
          name: xpf
          path: ${{github.workspace}}/artifacts/packages/Avalonia.Xpf.Controls.WebView.*.nupkg
          retention-days: 1

  publish-nightly-release:
    runs-on: [self-hosted, Linux]
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:

      - uses: actions/download-artifact@v4
        with:
            name: xpf
            path: ./nupkgs
      - uses: actions/download-artifact@v4
        with:
            name: avalonia
            path: ./nupkgs

      - name: Publish Nightly release
        run: dotnet nuget push ./nupkgs/**/*.nupkg  --api-key ${{secrets.INTERNAL_FEED_API_KEY}} --source ${{ vars.INTERNAL_FEED_UPLOAD_URL }}

      - name: Clean packages
        if: always()
        run: rm -rf ./nupkgs

  publish-xpf-release:
    runs-on: [self-hosted, Linux]
    needs: build
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:

    - uses: actions/download-artifact@v4
      with:
        name: xpf
        path: ./nupkgs

    - name: Publish XPF release
      run: dotnet nuget push ./nupkgs/**/*.nupkg  --api-key ${{secrets.baget_api_key}} --source ${{ vars.BAGET_API_URL }}

    - name: Clean packages
      if: always()
      run: rm -rf ./nupkgs

  publish-accelerate-release:
    runs-on: [self-hosted, Linux]
    needs: build
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:

    - uses: actions/download-artifact@v4
      with:
        name: avalonia
        path: ./nupkgs

    - name: Publish release
      run: dotnet nuget push ./nupkgs/**/*.nupkg --api-key ${{secrets.PROPACK_FEED_API_KEY}} --source ${{ vars.PROPACK_FEED_UPLOAD_URL }}

    - name: Clean packages
      if: always()
      run: rm -rf ./nupkgs
