name: Nightly

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  nightly:
    uses: AvaloniaUI/build-common/.github/workflows/library-cicd.yml@main
    with:
      install_workloads: "android"
      artifact_glob: Avalonia.Controls.WebView.*.nupkg
      nuget_feed: ${{ vars.NIGHTLY_FEED_UPLOAD_URL }}
    secrets:
      checkout_token: ${{ secrets.SUBMODULE_TOKEN }}
      nuget_api_key: ${{secrets.NIGHTLY_FEED_API_KEY}}
